-- =====================================================================
--  Миграция 0004: дополнительные графы свидетельства.
--
--  Полностью неразрушающая: только ADD COLUMN IF NOT EXISTS и
--  CREATE TABLE IF NOT EXISTS. Существующие данные не трогаются,
--  у уже заведённых свидетельств новые поля остаются пустыми (NULL /
--  без связей) и доступны к заполнению через админку.
--
--  Добавляет:
--    1) Две необязательные графы-колонки в таблицу note (храним, никуда
--       не выводим, заполняем через админ-панель):
--         • localization_accuracy — «Точность локализации»
--           («Эллипсис» / «Точное место»);
--         • place_type — «Тип места» (место жительства / работы /
--           …близких, родных, знакомых / «Другое»).
--    2) Четыре тегоподобных справочника (id + name) и их связи M2M
--       с note — по образцу tag / note_to_tag:
--         • organization  / note_to_organization  — «Упоминание/связанные организации»
--         • city_name     / note_to_city_name      — «Упоминание городских названий»
--         • geo_name      / note_to_geo_name        — «Упоминание географических названий»
--         • personality   / note_to_personality     — «Упоминание персоналий»
--
--  Применить к запущенной БД (из папки code):
--    docker compose exec -T db psql -U root -d db < ./database-core/migrations/0004_note_extra_fields.sql
--
--  На чистой базе таблицы и колонки таксономий создаются из моделей
--  (create_all). НО колонки note.localization_accuracy / note.place_type
--  create_all к уже существующей таблице note НЕ добавляет — для
--  заполненной базы эта миграция обязательна.
-- =====================================================================

BEGIN;

-- 1) Новые колонки на свидетельстве (необязательные).
ALTER TABLE note
    ADD COLUMN IF NOT EXISTS localization_accuracy text,
    ADD COLUMN IF NOT EXISTS place_type            text;

-- 2) Тегоподобные справочники + связи M2M.
--    Тип name — VARCHAR(255), как у прочих справочников (ExtendedBaseClass).

-- 2.1 Организации
CREATE TABLE IF NOT EXISTS organization (
    organization_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(255) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS note_to_organization (
    note_id         smallint NOT NULL REFERENCES note(note_id),
    organization_id smallint NOT NULL REFERENCES organization(organization_id),
    PRIMARY KEY (note_id, organization_id)
);

-- 2.2 Городские названия
CREATE TABLE IF NOT EXISTS city_name (
    city_name_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(255) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS note_to_city_name (
    note_id      smallint NOT NULL REFERENCES note(note_id),
    city_name_id smallint NOT NULL REFERENCES city_name(city_name_id),
    PRIMARY KEY (note_id, city_name_id)
);

-- 2.3 Географические названия
CREATE TABLE IF NOT EXISTS geo_name (
    geo_name_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS note_to_geo_name (
    note_id     smallint NOT NULL REFERENCES note(note_id),
    geo_name_id smallint NOT NULL REFERENCES geo_name(geo_name_id),
    PRIMARY KEY (note_id, geo_name_id)
);

-- 2.4 Персоналии
CREATE TABLE IF NOT EXISTS personality (
    personality_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(255) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS note_to_personality (
    note_id        smallint NOT NULL REFERENCES note(note_id),
    personality_id smallint NOT NULL REFERENCES personality(personality_id),
    PRIMARY KEY (note_id, personality_id)
);

COMMIT;
